### ISSUE TITLE
Module load error

### ISSUE THREAD

**Issue by bekirgulmus** [nadirhamid/asterisk-audiofork#6]
[Nov  3 21:12:21] ERROR[51505]: loader.c:281 module_load_error: Error loading module 'app_audiofork.so': /usr/lib/asterisk/modules/app_audiofork.so: undefined symbol: __PLEASE_USE_strtok_r_INSTEAD_OF_strtok__

and 
pbx.c:2927 pbx_extension_helper: No application 'AudioFork' for extension (from-internal, 1, 3)

**Comment by nadirhamid** [comment]
Hello @bekirgulmus,

Thanks for filing an issue.

Which version of Asterisk are you using ?

**Comment by ToToStranger** [comment]
Hi, i have the same issue.
I'm trying newest version of asterisk -18.1

**Comment by nadirhamid** [comment]
Hello @ToToStranger,

This issue should be resolved in commit d896b1d669af4892a914ea5433acdd4df0aaeba5.

If you still have any issues please feel free to file another issue.

thanks
