### ISSUE TITLE
Compilation error (asterisk 16.15.0)

### ISSUE THREAD

**Issue by varlog11** [nadirhamid/asterisk-audiofork#8]
Hi! 
When compiling, it gives an error

  [CC] app_audiofork.c -> app_audiofork.o
app_audiofork.c: In function ‘audiofork_exec’:
app_audiofork.c:900:38: error: expected ‘;’ before ‘pos’
         pt = strtok_r(NULL,",",&rest)
                                      ^
                                      ;
        pos = pos + 1;
        ~~~

**Comment by nadirhamid** [comment]
Fixed. if any issues still arise please feel free to create another issue. Thanks
