### ISSUE TITLE
Compilation error (asterisk 11.17.1)

### ISSUE THREAD

**Issue by sinoee** [nadirhamid/asterisk-audiofork#9]
[CC] app_audiofork.c -> app_audiofork.o
app_audiofork.c:57:35: error: asterisk/format_cache.h: No such file or directory
app_audiofork.c:58:27: error: asterisk/beep.h: No such file or directory
app_audiofork.c:314: error: expected specifier-qualifier-list before ‘ast_callid’
app_audiofork.c: In function ‘destroy_monitor_audiohook’:
app_audiofork.c:409: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:410: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:411: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:412: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c: In function ‘audiofork_free’:
app_audiofork.c:436: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:437: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:438: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:439: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:447: error: ‘struct audiofork’ has no member named ‘__field_mgr’
app_audiofork.c:447: error: ‘struct audiofork’ has no member named ‘__field_mgr_pool’
app_audiofork.c: In function ‘audiofork_thread’:
app_audiofork.c:457: error: storage size of ‘result’ isn’t known
app_audiofork.c:458: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:462: error: ‘struct audiofork’ has no member named ‘has_tls’
app_audiofork.c:464: warning: implicit declaration of function ‘ast_websocket_client_create’
app_audiofork.c:464: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:468: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:472: error: ‘WS_OK’ undeclared (first use in this function)
app_audiofork.c:472: error: (Each undeclared identifier is reported only once
app_audiofork.c:472: error: for each function it appears in.)
app_audiofork.c:479: error: ‘struct audiofork’ has no member named ‘callid’
app_audiofork.c:480: error: ‘struct audiofork’ has no member named ‘callid’
app_audiofork.c:487: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:489: warning: implicit declaration of function ‘ast_format_cache_get_slin_by_rate’
app_audiofork.c:489: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:491: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:540: error: ‘struct audiofork’ has no member named ‘flags’
app_audiofork.c:540: warning: type defaults to ‘int’ in declaration of ‘__p’
app_audiofork.c:540: error: ‘struct audiofork’ has no member named ‘flags’
app_audiofork.c:540: warning: comparison of distinct pointer types lacks a cast
app_audiofork.c:540: error: ‘struct audiofork’ has no member named ‘flags’
app_audiofork.c:541: warning: implicit declaration of function ‘ast_autochan_channel_lock’
app_audiofork.c:541: error: ‘struct audiofork’ has no member named ‘autochan’
app_audiofork.c:542: error: ‘struct audiofork’ has no member named ‘autochan’
app_audiofork.c:543: warning: implicit declaration of function ‘ast_autochan_channel_unlock’
app_audiofork.c:543: error: ‘struct audiofork’ has no member named ‘autochan’
app_audiofork.c:546: error: ‘struct audiofork’ has no member named ‘autochan’
app_audiofork.c:549: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:550: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:551: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:551: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:554: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c:457: warning: unused variable ‘result’
app_audiofork.c: In function ‘setup_audiofork_ds’:
app_audiofork.c:601: error: ‘struct audiofork’ has no member named ‘flags’
app_audiofork.c:601: warning: type defaults to ‘int’ in declaration of ‘__p’
app_audiofork.c:601: error: ‘struct audiofork’ has no member named ‘flags’
app_audiofork.c:601: warning: comparison of distinct pointer types lacks a cast
app_audiofork.c:601: error: ‘struct audiofork’ has no member named ‘flags’
app_audiofork.c:602: error: ‘struct audiofork’ has no member named ‘autochan’
app_audiofork.c:603: error: ‘struct audiofork’ has no member named ‘autochan’
app_audiofork.c:604: error: ‘struct audiofork’ has no member named ‘autochan’
app_audiofork.c:619: error: ‘struct audiofork’ has no member named ‘audiofork_ds’
app_audiofork.c: In function ‘launch_audiofork_thread’:
app_audiofork.c:664: error: ‘struct audiofork’ has no member named ‘__field_mgr’
app_audiofork.c:664: error: ‘struct audiofork’ has no member named ‘__field_mgr_pool’
app_audiofork.c:677: error: ‘struct audiofork’ has no member named ‘flags’
app_audiofork.c:678: error: ‘struct audiofork’ has no member named ‘autochan’
app_audiofork.c:690: error: ‘struct audiofork’ has no member named ‘has_tls’
app_audiofork.c:695: error: ‘struct audiofork’ has no member named ‘has_tls’
app_audiofork.c:720: error: ‘struct audiofork’ has no member named ‘autochan’
app_audiofork.c:740: error: ‘struct audiofork’ has no member named ‘flags’
app_audiofork.c:740: warning: type defaults to ‘int’ in declaration of ‘__p’
app_audiofork.c:740: error: ‘struct audiofork’ has no member named ‘flags’
app_audiofork.c:740: warning: comparison of distinct pointer types lacks a cast
app_audiofork.c:740: error: ‘struct audiofork’ has no member named ‘flags’
app_audiofork.c:741: error: ‘AST_AUDIOHOOK_SUBSTITUTE_SILENCE’ undeclared (first use in this function)
app_audiofork.c:758: error: ‘struct audiofork’ has no member named ‘callid’
app_audiofork.c: In function ‘audiofork_exec’:
app_audiofork.c:853: warning: implicit declaration of function ‘ast_beep_start’
app_audiofork.c: In function ‘stop_audiofork_full’:
app_audiofork.c:996: warning: implicit declaration of function ‘ast_beep_stop’
app_audiofork.c: At top level:
app_audiofork.c:1336: error: unknown field ‘support_level’ specified in initializer
app_audiofork.c:1336: error: ‘AST_MODULE_SUPPORT_CORE’ undeclared here (not in a function)
app_audiofork.c:1336: error: unknown field ‘optional_modules’ specified in initializer
app_audiofork.c:1336: warning: initialization from incompatible pointer type
make[1]: *** [app_audiofork.o] Error 1
make: *** [apps] Error 2

**Comment by nadirhamid** [comment]
Hello @sinoee,

This module has only been tested on Asterisk version 16 and later. It will likely not work on versions prior. As a result, I suggest either upgrading or finding another solution.

If you have any other questions need more info let me know.

Thanks

**Comment by masteringvoip** [comment]
hi @nadirhamid 

It also not working on asterisk 16 / segfault fault 

Here is the error:

asterisk-tts*CLI> module show like audiofork
Module                         Description                              Use Count  Status      Support Level
app_audiofork.so               Audio Forking application                0          Running              core
1 modules loaded


asterisk-tts*CLI> audiofork list
Usage: audiofork start <chan_name> [args]
         The optional arguments are passed to the AudioFork application.
       audiofork stop <chan_name> [args]
         The optional arguments are passed to the StopAudioFork application.
       audiofork list <chan_name>
  == Using SIP RTP TOS bits 184
  == Using SIP RTP CoS mark 5
       > 0x7f35dc008ad0 -- Strict RTP learning after remote address set to: 202.52.48.210:4002
    -- Executing [7000@main-out:1] Answer("SIP/9999-00000000", "") in new stack
    -- Executing [7000@main-out:2] Verbose("SIP/9999-00000000", "starting audio fork") in new stack
starting audio fork
    -- Executing [7000@main-out:3] AudioFork("SIP/9999-00000000", "ws://localhost:8080/") in new stack
  == setting wsserver to ws://localhost:8080/
  == setting direction to 2
       > 0x7f35dc008ad0 -- Strict RTP learning after remote address set to: 202.52.48.210:4002
asterisk-tts*CLI>
Disconnected from Asterisk server
Asterisk cleanly ending (0).
Executing last minute cleanups
Asterisk ending (0).

[root@asterisk-tts asterisk-16.16.2]# dmesg
[92488.239632] asterisk[14000]: segfault at 88 ip 00007f36b14e7a7d sp 00007f36b73d42e0 error 4 in app_audiofork.so[7f36b14e3000+9000]
[92598.178537] asterisk[14178]: segfault at 88 ip 00007fb7910e5a7d sp 00007fb791b462e0 error 4 in app_audiofork.so[7fb7910e1000+9000]
[92873.266843] asterisk[17954]: segfault at 88 ip 00007f35e2cfda7d sp 00007f35763882e0 error 4 in app_audiofork.so[7f35e2cf9000+9000]

**Comment by dix83** [comment]
app_audiofork.c: In function ‘launch_audiofork_thread’:
app_audiofork.c:875:39: error: ‘AST_AUDIOHOOK_SUBSTITUTE_SILENCE’ undeclared (first use in this function)
   ast_set_flag(&audiofork->audiohook, AST_AUDIOHOOK_SUBSTITUTE_SILENCE);
                                       ^
/usr/src/asterisk/asterisk-16.0.1/include/asterisk/utils.h:74:22: note: in definition of macro ‘ast_set_flag’
      ((p)->flags |= (flag)); \
                      ^
app_audiofork.c:875:39: note: each undeclared identifier is reported only once for each function it appears in
   ast_set_flag(&audiofork->audiohook, AST_AUDIOHOOK_SUBSTITUTE_SILENCE);
                                       ^
/usr/src/asterisk/asterisk-16.0.1/include/asterisk/utils.h:74:22: note: in definition of macro ‘ast_set_flag’
      ((p)->flags |= (flag)); \
                      ^
make[1]: *** [app_audiofork.o] Error 1
make: *** [apps] Error 2

Same problem

core show version
Asterisk 16.0.1 built by root @ localhost.localdomain on a x86_64 running Linux on 2022-05-04 11:25:08 UTC
